apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
  
resources:
  - resources/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/ha/install.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-server-deployment.yaml
  - patches/argocd-repo-server-deployment.yaml
  - patches/argocd-application-controller-statefulset.yaml